import { Navigation } from './components/Navigation'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <header><Navigation /></header>
          <main>
            { children }
          </main>
          <footer><p>© Сделано на React, Next.js</p></footer>
        </div>
      </body>
    </html>
  )
}